(define (problem hero_problem_3)
   (:domain CMI7504-2526_solution)
   (:objects 
      rooma roomb roomc roomd roome roomf roomg roomh roomi roomj roomk rooml roomm roomn roomo roomp roomq roomr rooms roomt - room
      trap1 trap2 trap3 trap4 trap5 trap6 - trap
      sword1 sword2 sword3 sword4 - sword
      monster1 monster2 monster3 monster4 monster5 monster6 monster7 - monster
   )
   (:init 
        (place rooma)
        (place roomb)
        (place roomc)
        (place roomd)
        (place roome)
        (place roomf)
        (place roomg)
        (place roomh)
        (place roomi)
        (place roomj)
        (place roomk)
        (place rooml)
        (place roomm)
        (place roomn)
        (place roomo)
        (place roomp)
        (place roomq)
        (place roomr)
        (place rooms)
        (place roomt)
        (place-not-destroyed-yet rooma)
        (place-not-destroyed-yet roomb)
        (place-not-destroyed-yet roomc)
        (place-not-destroyed-yet roomd)
        (place-not-destroyed-yet roome)
        (place-not-destroyed-yet roomf)
        (place-not-destroyed-yet roomg)
        (place-not-destroyed-yet roomh)
        (place-not-destroyed-yet roomi)
        (place-not-destroyed-yet roomj)
        (place-not-destroyed-yet roomk)
        (place-not-destroyed-yet rooml)
        (place-not-destroyed-yet roomm)
        (place-not-destroyed-yet roomn)
        (place-not-destroyed-yet roomo)
        (place-not-destroyed-yet roomp)
        (place-not-destroyed-yet roomq)
        (place-not-destroyed-yet roomr)
        (place-not-destroyed-yet rooms)
        (place-not-destroyed-yet roomt)

        (corridor rooma roomb)
        (corridor roomb rooma)
        (corridor rooma roomf)
        (corridor roomf rooma)

        (corridor roomb roomc)
        (corridor roomc roomb)
        (corridor roomb roomg)
        (corridor roomg roomb)

        (corridor roomc roomd)
        (corridor roomd roomc)
        (corridor roomc roomh)
        (corridor roomh roomc)

        (corridor roomd roome)
        (corridor roome roomd)
        (corridor roomd roomi)
        (corridor roomi roomd)

        (corridor roome roomj)
        (corridor roomj roome)

        (corridor roomf roomg)  
        (corridor roomg roomf)
        (corridor roomf roomk)
        (corridor roomk roomf)

        (corridor roomg roomh)
        (corridor roomh roomg)
        (corridor roomg rooml)
        (corridor rooml roomg)

        (corridor roomh roomi)
        (corridor roomi roomh)
        (corridor roomh roomm)
        (corridor roomm roomh)  

        (corridor roomi roomj)
        (corridor roomj roomi)
        (corridor roomi roomn)
        (corridor roomn roomi)

        (corridor roomj roomo)
        (corridor roomo roomj)

        (corridor roomk rooml)
        (corridor rooml roomk)
        (corridor roomk roomp)
        (corridor roomp roomk)

        (corridor rooml roomm)
        (corridor roomm rooml)
        (corridor rooml roomq)
        (corridor roomq rooml)

        (corridor roomm roomn)
        (corridor roomn roomm)
        (corridor roomm roomr)
        (corridor roomr roomm)

        (corridor roomn roomo)
        (corridor roomo roomn)
        (corridor roomn rooms)
        (corridor rooms roomn)

        (corridor roomo roomt)
        (corridor roomt roomo)

        (corridor roomk rooml)
        (corridor rooml roomk)

        (corridor roomp roomq)
        (corridor roomq roomp)        

        (corridor roomq roomr)
        (corridor roomr roomq)        
        
        (corridor roomr rooms)
        (corridor rooms roomr)  

        (corridor rooms roomt)
        (corridor roomt rooms)        
     
        (at-hero rooma)

        (is-sword sword1)
        (is-sword sword2)
        (is-sword sword3)
        (is-sword sword4)
        (sword-not-destroyed-yet sword1)
        (sword-not-destroyed-yet sword2)
        (sword-not-destroyed-yet sword3)
        (sword-not-destroyed-yet sword4)
        (at-sword roomc sword1)
        (at-sword roomj sword2)
        (at-sword roomm sword3)
        (at-sword roomp sword4)

        (at-monster roomb monster1)
        (at-monster roomd monster2)
        (at-monster roomg monster3)
        (at-monster roomi monster4)
        (at-monster roomn monster5)
        (at-monster roomq monster6)
        (at-monster roomr monster7)

        (is-trap trap1)
        (is-trap trap2)
        (is-trap trap3)
        (is-trap trap4)
        (is-trap trap5)
        (is-trap trap6)
        (at-trap roome trap1)
        (at-trap roomh trap2)
        (at-trap roomk trap3)
        (at-trap rooml trap4)
        (at-trap roomo trap5)
        (at-trap rooms trap6)
        (with-trap roome)
        (with-trap roomh)
        (with-trap roomk)
        (with-trap rooml)
        (with-trap roomo)
        (with-trap rooms)

        (hands-free)

               )
   (:goal (at-hero roomt))
)
