(define (problem get_out)
   (:domain the-dungeon)
   (:objects rooma roomb roomc roomd roome roomf roomg roomh)
   (:init 
        (room rooma)
        (room roomb)
        (room roomc)
        (room roomd)
        (room roome)
        (room roomf)
        (room roomg)
        (room roomh)
        (room rooma)
        (not-destroyed-yet rooma)
        (not-destroyed-yet roomb)
        (not-destroyed-yet roomc)
        (not-destroyed-yet roomd)
        (not-destroyed-yet roome)
        (not-destroyed-yet roomf)
        (not-destroyed-yet roomg)
        (not-destroyed-yet roomh)
        (corridor rooma roomb)
        (corridor roomb rooma)
        (corridor rooma roomc)
        (corridor roomc rooma)
        (corridor roomb roomc)
        (corridor roomc roomb)
        (corridor roomb roomd)
        (corridor roomd roomb)
        (corridor roomc roome)
        (corridor roome roomc)
        (corridor roomd roome)
        (corridor roome roomd)
        (corridor roomd roomf)
        (corridor roomf roomd)
        (corridor roome roomg)
        (corridor roomg roome)
        (corridor roomf roomh)
        (corridor roomh roomf)
        (corridor roomf roomg)
        (corridor roomg roomf)
        (at-hero rooma)
        
               )
   (:goal (and
      (at-hero roomh)
                            )))
