(define (problem get_out)
   (:domain the-dungeon)
   (:objects rooma roomb roomc roomd roome roomf roomg roomh)
   (:init 
        (place rooma)
        (place roomb)
        (place roomc)
        (place roomd)
        (place roome)
        (place roomf)
        (place roomg)
        (place roomh)
        (place-not-destroyed-yet rooma)
        (place-not-destroyed-yet roomb)
        (place-not-destroyed-yet roomc)
        (place-not-destroyed-yet roomd)
        (place-not-destroyed-yet roome)
        (place-not-destroyed-yet roomf)
        (place-not-destroyed-yet roomg)
        (place-not-destroyed-yet roomh)
        (corridor rooma roomb)
        (corridor roomb rooma)
        (corridor rooma roomc)
        (corridor roomc rooma)
        (corridor roomb roomc)
        (corridor roomc roomb)
        (corridor roomb roomd)
        (corridor roomd roomb)
        (corridor roomc roome)
        (corridor roome roomc)
        (corridor roomd roome)
        (corridor roome roomd)
        (corridor roomd roomf)
        (corridor roomf roomd)
        (corridor roome roomg)
        (corridor roomg roome)
        (corridor roomf roomh)
        (corridor roomh roomf)
        (corridor roomf roomg)
        (corridor roomg roomf)
        (at-hero rooma)        
               )
   (:goal (at-hero roomh))
)