(define (problem get_out)
   (:domain the-dungeon)
   (:objects rooma roomb roomc roomd roome roomf roomg roomh)
   (:init 
        (room rooma)
        (room roomb)
        (room roomc)
        (room roomd)
        (room roome)
        (room roomf)
        (room roomg)
        (room roomh)
        (corridor rooma roomb)
        (corridor rooma roomc)
        (corridor roomb roomc)
        (corridor roomb roomd)
        (corridor roomc roome)
        (corridor roomd roome)
        (corridor roomd roomf)
        (corridor roome roomg)
        (corridor roomf roomh)
        (corridor roomf roomg)
        (at-hero rooma)
        
               )
   (:goal (and 
                (at-hero roomh)
                )))
